export const IMAGE_EDITOR_COMPUTED_CROP = "IMAGE_EDITOR_COMPUTED_CROP";
export const IMAGE_EDITOR_CROP = "IMAGE_EDITOR_CROP";
export const IMAGE_EDITOR_FLIP = "IMAGE_EDITOR_FLIP";
export const IMAGE_EDITOR_IMAGE_HAS_LOADED = "IMAGE_EDITOR_IMAGE_HAS_LOADED";
export const IMAGE_EDITOR_ROTATE_COUNTERCLOCKWISE =
  "IMAGE_EDITOR_ROTATE_COUNTERCLOCKWISE";
export const IMAGE_EDITOR_SET_ASPECT_RATIO = "IMAGE_EDITOR_SET_ASPECT_RATIO";
export const IMAGE_EDITOR_SET_CROP_BOUNDS = "IMAGE_EDITOR_SET_CROP_BOUNDS";
export const IMAGE_EDITOR_SET_DEFAULT_ASPECT_RATIO =
  "IMAGE_EDITOR_SET_DEFAULT_ASPECT_RATIO";
export const IMAGE_EDITOR_SET_FILE_INFO = "IMAGE_EDITOR_SET_FILE_INFO";
export const IMAGE_EDITOR_STATE_RESET = "IMAGE_EDITOR_STATE_RESET";
export const IMAGE_EDITOR_STATE_RESET_ALL = "IMAGE_EDITOR_STATE_RESET_ALL";


export const APPLY_STORED_STATE = 'APPLY_STORED_STATE';


export const DESERIALIZE = 'DESERIALIZE';


export const SERIALIZE = 'SERIALIZE';
